### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by parvez85** [parvez85/prework-study-guide#2]
# CSS

##  User Story
As a boot camp student
I want the prework notes to be structured on a webpage 
so that I can easily find and read the information

## Acceptance Criteria

GIVEN a prework Study Guide website
WHEN I view the study guide
THEN I see a dark blue header and footer, and four boxes with a shadow

**Comment by Anirudh-Madhav-Kulkarni** [comment]
<h1>can you clearly mention what the issue is so that I can help you to solve it</h1>
